version: '3.8'
services:
   catalogdb:
    image: mongo
   basketdb:
    image:  redis
   discountdb:
    image: postgres
   identitydb:
    image:  mcr.microsoft.com/mssql/server:2019-latest
   orderdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
   rabbitmq:
    image: rabbitmq:3.8.14-management
   catalog.api:
    image: catalog_api_image
    build: 
     context: .
     dockerfile: Services/CatalogService/Catalog.Service.API/Dockerfile
   identityserver.api:
    image: identityserver_api_image
    build: 
     context: .
     dockerfile: IdentityServer/Dockerfile
   basket.api:
    image: basket_api_image
    build: 
     context: .
     dockerfile: Services/BasketService/BasketService.API/Dockerfile
   photostock.api:
    image: photostock_api_image
    build: 
     context: .
     dockerfile: Services/PhotoStockService/PhotoStockService.API/Dockerfile
   discount.api:
    image: discount_api_image
    build: 
     context: .
     dockerfile: Services/DiscountService/DiscountService.API/Dockerfile
   fakepayment.api:
    image: fakepayment_api_image
    build: 
     context: .
     dockerfile: Services/FakePaymentService/FakePaymentService.API/Dockerfile
   order.api:
    image: order_api_image
    build: 
     context: .
     dockerfile: Services/OrderService/OrderService.API/Dockerfile
   gateway.api:
    image: gateway_api_image
    build: 
     context: .
     dockerfile: GatewayAPI/Gateway.API/Dockerfile
   aspnetcoremvc.web:
    image: aspnetcoremvc.web_image
    build:
     context: .
     dockerfile: CoursesUI/Course.Web/Dockerfile

volumes:
  catalogdb_volume:
  discount_volume:
  identity_volume:
  orderdb_volume:
